Repository redis/lettuce, pull requests merged in 2021-03, with the labels that each got.

#1632 Typo in string reactive commands
  src/main/java/io/lettuce/core/api/reactive/RedisStringReactiveCommands.java
Labels: type: documentation

#1648 Fix ScoredValueUnitTests
  src/test/java/io/lettuce/core/ScoredValueUnitTests.java
Labels: type: regression

#1603 Fix formatting indent in kotlin files
  src/main/kotlin/io/lettuce/core/ExperimentalLettuceCoroutinesApi.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisCoroutinesCommandsImpl.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisKeyCoroutinesCommandsImpl.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisListCoroutinesCommandsImpl.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisSortedSetCoroutinesCommandsImpl.kt
  src/main/kotlin/io/lettuce/core/cluster/api/coroutines/RedisClusterCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/cluster/api/coroutines/RedisClusterCoroutinesCommandsImpl.kt
Labels: type: task

#1661 Fix travis links due to its domain name migration
  README.md
  pom.xml
Labels: type: task

#1666 Rename zrandmemberWithscores to zrandmemberWithScores
  src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
  src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
  src/main/java/io/lettuce/core/RedisCommandBuilder.java
  src/main/java/io/lettuce/core/api/async/RedisSortedSetAsyncCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisSortedSetReactiveCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisSortedSetCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionSortedSetAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionSortedSetCommands.java
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisSortedSetCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisSortedSetCoroutinesCommandsImpl.kt
  src/main/templates/io/lettuce/core/api/RedisSortedSetCommands.java
  src/test/java/io/lettuce/core/commands/SortedSetCommandIntegrationTests.java
Labels: type: task

#1673 Add support CLIENT KILL USER
  src/main/java/io/lettuce/core/KillArgs.java
  src/test/java/io/lettuce/core/commands/ServerCommandIntegrationTests.java
Labels: type: enhancement
