Repository redis/lettuce, pull requests merged in 2024-08, with the labels that each got.

#2862 Add support for CLIENT TRACKINGINFO
  src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
  src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
  src/main/java/io/lettuce/core/RedisCommandBuilder.java
  src/main/java/io/lettuce/core/TrackingInfo.java
  src/main/java/io/lettuce/core/api/async/RedisServerAsyncCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisServerReactiveCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisServerCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionServerAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionServerCommands.java
  src/main/java/io/lettuce/core/output/ArrayComplexData.java
  src/main/java/io/lettuce/core/output/ComplexData.java
  src/main/java/io/lettuce/core/output/ComplexDataParser.java
  src/main/java/io/lettuce/core/output/ComplexOutput.java
  src/main/java/io/lettuce/core/output/MapComplexData.java
  src/main/java/io/lettuce/core/output/SetComplexData.java
  src/main/java/io/lettuce/core/output/TrackingInfoParser.java
  src/main/java/io/lettuce/core/protocol/CommandKeyword.java
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisServerCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisServerCoroutinesCommandsImpl.kt
  src/main/templates/io/lettuce/core/api/RedisServerCommands.java
  src/test/java/io/lettuce/core/RedisCommandBuilderUnitTests.java
  src/test/java/io/lettuce/core/commands/ServerCommandIntegrationTests.java
  src/test/java/io/lettuce/core/output/TrackingInfoParserTest.java
Labels: type: feature

#2944 Convert wiki to markdown docs
  .github/CONTRIBUTING.md
  .github/wordlist.txt
  .github/workflows/docs.yml
  README.md
  docs/advanced-usage.md
  docs/faq.md
  docs/getting-started.md
  docs/ha-sharding.md
  docs/index.md
  docs/integration-extension.md
  docs/new-features.md
  docs/overview.md
  docs/redis-command-interfaces.md
  docs/static/logo-redis.svg
  docs/user-guide/async-api.md
  docs/user-guide/connecting-redis.md
  docs/user-guide/kotlin-api.md
  docs/user-guide/lua-scripting.md
  docs/user-guide/pubsub.md
  docs/user-guide/reactive-api.md
  docs/user-guide/redis-functions.md
  docs/user-guide/transactions-multi.md
  mkdocs.yml
  pom.xml
  src/main/asciidoc/advanced-usage.asciidoc
  src/main/asciidoc/faq.asciidoc
  src/main/asciidoc/getting-started.asciidoc
  src/main/asciidoc/ha-sharding.asciidoc
  src/main/asciidoc/images/apple-touch-icon-144.png
  src/main/asciidoc/images/apple-touch-icon-180.png
  src/main/asciidoc/images/lettuce-green-text@2x.png
  src/main/asciidoc/images/touch-icon-192x192.png
  src/main/asciidoc/index-docinfo.html
  src/main/asciidoc/index.asciidoc
  src/main/asciidoc/integration-extension.asciidoc
  src/main/asciidoc/kotlin-api.asciidoc
  src/main/asciidoc/new-features.adoc
  src/main/asciidoc/overview.asciidoc
  src/main/asciidoc/redis-command-interfaces.asciidoc
  src/main/asciidoc/scripting-and-functions.asciidoc
  src/main/asciidoc/stylesheets/golo.css
Labels: type: documentation, type: dependency-upgrade, type: task

#2972 fix(2971): spublish typo fix
  src/main/java/io/lettuce/core/pubsub/RedisPubSubReactiveCommandsImpl.java
Labels: type: bug

#2975 (crossport to 6.4.x) spublish typo fix (#2972)
  src/main/java/io/lettuce/core/pubsub/RedisPubSubReactiveCommandsImpl.java
Labels: type: bug
