Repository redis/lettuce, pull requests merged in 2024-09, with the labels that each got.

#2980 Update completeExceptionally on ClusterCommand using super
  src/main/java/io/lettuce/core/cluster/ClusterCommand.java
Labels: type: bug

#2927 Default ClientOptions.timeoutOptions to TimeoutOptions.enabled()
  src/main/java/io/lettuce/core/ClientOptions.java
  src/test/java/io/lettuce/core/ClientOptionsIntegrationTests.java
  src/test/java/io/lettuce/core/cluster/RedisClusterSetupTest.java
  src/test/java/io/lettuce/core/protocol/ConnectionFailureIntegrationTests.java
  src/test/java/io/lettuce/core/reliability/AtLeastOnceTest.java
  src/test/java/io/lettuce/core/reliability/AtMostOnceTest.java
Labels: type: feature

#2995 Bits and pieces to clean up
  .github/CONTRIBUTING.md
  .github/wordlist.txt
  README.md
  docs/new-features.md
  docs/user-guide/redis-json.md
  src/main/java/io/lettuce/core/api/reactive/RedisHashReactiveCommands.java
  src/main/kotlin/io/lettuce/core/ScanFlow.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/BaseRedisCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisHashCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisScriptingCoroutinesCommands.kt
  src/main/resources/META-INF/LICENSE
  src/main/resources/META-INF/NOTICE
Labels: type: documentation

#3001 Bits and pieces to clean up (#2995)
  .github/CONTRIBUTING.md
  .github/wordlist.txt
  README.md
  docs/new-features.md
  docs/user-guide/redis-json.md
  src/main/java/io/lettuce/core/api/reactive/RedisHashReactiveCommands.java
  src/main/kotlin/io/lettuce/core/ScanFlow.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/BaseRedisCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisHashCoroutinesCommands.kt
  src/main/kotlin/io/lettuce/core/api/coroutines/RedisScriptingCoroutinesCommands.kt
  src/main/resources/META-INF/LICENSE
  src/main/resources/META-INF/NOTICE
Labels: type: documentation, type: task
