Repository redis/lettuce, pull requests merged in 2024-06, with the labels that each got.

#2881 Setting the next release to be 6.4.x as part of #2880
  pom.xml
  src/main/java/io/lettuce/core/KillArgs.java
  src/main/java/io/lettuce/core/ScanIterator.java
  src/main/java/io/lettuce/core/ScanStream.java
  src/main/java/io/lettuce/core/XReadArgs.java
  src/main/java/io/lettuce/core/api/async/BaseRedisAsyncCommands.java
  src/main/java/io/lettuce/core/api/async/RedisHashAsyncCommands.java
  src/main/java/io/lettuce/core/api/async/RedisKeyAsyncCommands.java
  src/main/java/io/lettuce/core/api/async/RedisScriptingAsyncCommands.java
  src/main/java/io/lettuce/core/api/reactive/BaseRedisReactiveCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisHashReactiveCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisKeyReactiveCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisScriptingReactiveCommands.java
  src/main/java/io/lettuce/core/api/sync/BaseRedisCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisHashCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisKeyCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisScriptingCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/BaseNodeSelectionAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionHashAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionKeyAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionScriptingAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/BaseNodeSelectionCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionHashCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionKeyCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionScriptingCommands.java
  src/main/java/io/lettuce/core/cluster/pubsub/RedisClusterPubSubListener.java
  src/main/java/io/lettuce/core/cluster/pubsub/api/async/NodeSelectionPubSubAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/pubsub/api/reactive/NodeSelectionPubSubReactiveCommands.java
  src/main/java/io/lettuce/core/cluster/pubsub/api/sync/NodeSelectionPubSubCommands.java
  src/main/java/io/lettuce/core/pubsub/RedisPubSubListener.java
  src/main/java/io/lettuce/core/pubsub/api/async/RedisPubSubAsyncCommands.java
  src/main/java/io/lettuce/core/pubsub/api/reactive/RedisPubSubReactiveCommands.java
  src/main/java/io/lettuce/core/pubsub/api/sync/RedisPubSubCommands.java
  src/main/templates/io/lettuce/core/api/BaseRedisCommands.java
  src/main/templates/io/lettuce/core/api/RedisHashCommands.java
  src/main/templates/io/lettuce/core/api/RedisKeyCommands.java
  src/main/templates/io/lettuce/core/api/RedisScriptingCommands.java
Labels: type: task

#2893 Updated release acton (as part of #2880)
  .github/workflows/version-and-release.yaml
Labels: type: documentation, type: task

#2871 Remove not readonly commands #2832
  src/main/java/io/lettuce/core/masterreplica/ReadOnlyCommands.java
  src/main/java/io/lettuce/core/protocol/ReadOnlyCommands.java
  src/test/java/io/lettuce/core/cluster/ClusterReadOnlyCommandsUnitTests.java
  src/test/java/io/lettuce/core/commands/HashCommandIntegrationTests.java
  src/test/java/io/lettuce/core/commands/ServerCommandIntegrationTests.java
Labels: type: bug

#2897 Fixed the release flow (6.4.x branch)
  .github/workflows/version-and-release.yaml
  pom.xml
Labels: type: documentation, type: dependency-upgrade, type: task
