Repository redis/lettuce, pull requests merged in 2024-12, with the labels that each got.

#3065 Restore API that was accidently deleted when introducing the JSON feature
  src/main/java/io/lettuce/core/StatefulRedisConnectionImpl.java
  src/main/java/io/lettuce/core/cluster/StatefulRedisClusterConnectionImpl.java
  src/main/java/io/lettuce/core/masterreplica/StatefulRedisMasterReplicaConnectionImpl.java
  src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
  src/main/java/io/lettuce/core/sentinel/StatefulRedisSentinelConnectionImpl.java
Labels: type: bug, type: blocker

#2953 fix: prevent blocking event loop thread by replacing ArrayDeque with HashIndexedQueue
  src/main/java/io/lettuce/core/ClientOptions.java
  src/main/java/io/lettuce/core/datastructure/queue/HashIndexedQueue.java
  src/main/java/io/lettuce/core/protocol/CommandHandler.java
  src/test/java/io/lettuce/core/datastructure/queue/HashIndexedQueueTests.java
Labels: type: feature

#2597 Fix: make sure FIFO order between write and notify channel active
  src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java
  src/test/java/io/lettuce/core/protocol/DefaultEndpointUnitTests.java
Labels: type: bug, status: waiting-for-feedback
