Repository redis/lettuce, pull requests merged in 2024-10, with the labels that each got.

#3008 Add the github repo url to the doc config
  mkdocs.yml
Labels: type: documentation

#3005 Propagate database number, user, and RedisURI into Tracing
  src/main/java/io/lettuce/core/protocol/CommandHandler.java
  src/test/java/io/lettuce/core/tracing/SynchronousIntegrationTests.java
Labels: type: feature

#3016 Add support for creating regex and subnet-based ReadFrom instances from a single string
  src/main/java/io/lettuce/core/ReadFrom.java
  src/test/java/io/lettuce/core/cluster/ReadFromUnitTests.java
Labels: type: feature

#3015 Add hasNoSlots() method to RedisClusterNode
  src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java
  src/test/java/io/lettuce/core/cluster/models/partitions/RedisClusterNodeUnitTests.java
Labels: type: feature

#3020 ScanIterator.scan.stream().toList() causes "java.lang.IllegalStateException: Accept exceeded fixed size of 0" on Java 16+ (#3002)
  src/main/java/io/lettuce/core/ScanIterator.java
Labels: type: bug

#3007 document update regarding addressResolverGroup settings
  docs/advanced-usage.md
  src/main/java/io/lettuce/core/resource/DefaultClientResources.java
Labels: type: documentation

#3023 Add CodeCov configuration, enable test analytics (#3022)
  .github/codecov.yml
  .github/workflows/integration.yml
  .github/workflows/release-drafter.yml
  .github/workflows/spellcheck.yml
Labels: type: task

#3024 Resubscribe logic ignoring Pub/Sub shard channels after reconnect. #2940
  src/main/java/io/lettuce/core/pubsub/PubSubEndpoint.java
  src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
  src/test/java/io/lettuce/core/pubsub/PubSubCommandIntegrationTests.java
  src/test/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImplUnitTests.java
Labels: type: bug

#3026 Sharded PubSub subscriptions not recovered after disconn… #2940
  src/main/java/io/lettuce/core/pubsub/PubSubEndpoint.java
  src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
  src/test/java/io/lettuce/core/pubsub/PubSubCommandTest.java
  src/test/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImplUnitTests.java
Labels: type: bug

#3033 Command interface - issues with async array results #2612
  src/main/java/io/lettuce/core/output/BooleanListOutput.java
  src/test/java/io/lettuce/core/commands/CommandInterfacesIntegrationTests.java
Labels: type: bug
