Repository redis/lettuce, pull requests merged in 2025-02, with the labels that each got.

#3150 Add support for FT.CREATE #2717
  src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
  src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
  src/main/java/io/lettuce/core/RediSearchCommandBuilder.java
  src/main/java/io/lettuce/core/api/async/RediSearchAsyncCommands.java
  src/main/java/io/lettuce/core/api/async/RedisAsyncCommands.java
  src/main/java/io/lettuce/core/api/reactive/RediSearchReactiveCommands.java
  src/main/java/io/lettuce/core/api/reactive/RedisReactiveCommands.java
  src/main/java/io/lettuce/core/api/sync/RediSearchCommands.java
  src/main/java/io/lettuce/core/api/sync/RedisCommands.java
  src/main/java/io/lettuce/core/cluster/api/async/RediSearchAsyncCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/RediSearchCommands.java
  src/main/java/io/lettuce/core/cluster/api/sync/RedisClusterCommands.java
  src/main/java/io/lettuce/core/protocol/CommandKeyword.java
  src/main/java/io/lettuce/core/protocol/CommandType.java
  src/main/java/io/lettuce/core/search/DocumentLanguage.java
  src/main/java/io/lettuce/core/search/Field.java
  src/main/java/io/lettuce/core/search/arguments/CreateArgs.java
  src/main/java/io/lettuce/core/search/package-info.java
  src/main/kotlin/io/lettuce/core/api/coroutines/RediSearchCoroutinesCommands.kt
  src/main/templates/io/lettuce/core/api/RediSearchCommands.java
  src/test/java/io/lettuce/apigenerator/Constants.java
  src/test/java/io/lettuce/core/RediSearchCommandBuilderUnitTests.java
  src/test/java/io/lettuce/core/json/RediSearchIntegrationTests.java
Labels: type: feature

#3147 Update CommonsPool2ConfigConverterUnitTests.java
  src/test/java/io/lettuce/core/support/CommonsPool2ConfigConverterUnitTests.java
Labels: type: task

#3179 ACL DELUSER does not work correctly with UTF-8 Japanese characters #3178
  .github/workflows/stale-issues.yml
  src/main/java/io/lettuce/core/output/ClaimedMessagesOutput.java
  src/main/java/io/lettuce/core/output/CommandOutput.java
  src/main/java/io/lettuce/core/output/DoubleListOutput.java
  src/main/java/io/lettuce/core/output/DoubleOutput.java
  src/main/java/io/lettuce/core/output/EnumSetOutput.java
  src/main/java/io/lettuce/core/output/GeoCoordinatesListOutput.java
  src/main/java/io/lettuce/core/output/GeoCoordinatesValueListOutput.java
  src/main/java/io/lettuce/core/output/GeoWithinListOutput.java
  src/main/java/io/lettuce/core/output/JsonTypeListOutput.java
  src/main/java/io/lettuce/core/output/KeyValueListScoredValueOutput.java
  src/main/java/io/lettuce/core/output/KeyValueOfScoredValueOutput.java
  src/main/java/io/lettuce/core/output/KeyValueScoredValueOutput.java
  src/main/java/io/lettuce/core/output/MultiOutput.java
  src/main/java/io/lettuce/core/output/NumberListOutput.java
  src/main/java/io/lettuce/core/output/PendingMessageListOutput.java
  src/main/java/io/lettuce/core/output/PendingMessagesOutput.java
  src/main/java/io/lettuce/core/output/ScanOutput.java
  src/main/java/io/lettuce/core/output/ScoredValueListOutput.java
  src/main/java/io/lettuce/core/output/ScoredValueOutput.java
  src/main/java/io/lettuce/core/output/ScoredValueScanOutput.java
  src/main/java/io/lettuce/core/output/ScoredValueScanStreamingOutput.java
  src/main/java/io/lettuce/core/output/ScoredValueStreamingOutput.java
  src/main/java/io/lettuce/core/output/SocketAddressOutput.java
  src/main/java/io/lettuce/core/output/StatusOutput.java
  src/main/java/io/lettuce/core/output/StreamMessageListOutput.java
  src/main/java/io/lettuce/core/output/StreamReadOutput.java
  src/main/java/io/lettuce/core/output/StringListOutput.java
  src/main/java/io/lettuce/core/output/StringValueListOutput.java
  src/main/java/io/lettuce/core/pubsub/PubSubOutput.java
  src/test/java/io/lettuce/core/commands/AclCommandIntegrationTests.java
  src/test/jmh/io/lettuce/core/dynamic/RedisCommandFactoryBenchmark.java
  src/test/resources/log4j2-test.xml
Labels: type: bug

#3148 Fix SimpleBatcher apparent deadlock #2196
  src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java
  src/test/java/io/lettuce/core/dynamic/SimpleBatcherUnitTests.java
Labels: type: bug
