Repository redis/lettuce, pull requests merged in 2025-03, with the labels that each got.

#3206 Exception on zpopmin (#3199)
  src/main/java/io/lettuce/core/json/DefaultJsonParser.java
  src/main/java/io/lettuce/core/json/UnproccessedJsonValue.java
  src/main/java/io/lettuce/core/output/JsonValueListOutput.java
  src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java
Labels: type: bug

#3167 Include command type in the timeout message
  src/main/java/io/lettuce/core/protocol/CommandExpiryWriter.java
Labels: type: improvement

#3095 docs: update Limitations section to reflect shaded JAR deprecation
  docs/advanced-usage.md
Labels: type: documentation

#3118 Introduce command replay filter to avoid command replaying after reconnect #1310
  .github/wordlist.txt
  docs/advanced-usage.md
  src/main/java/io/lettuce/core/ClientOptions.java
  src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java
  src/test/java/io/lettuce/core/cluster/ClusterNodeEndpointUnitTests.java
  src/test/java/io/lettuce/core/reliability/AtLeastOnceIntegrationTests.java
Labels: type: feature
